### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by avijit9** [SoccerNet/sn-spotting#2]
Hi,

Thanks for this awesome dataset!

I would like to go through the evaluation code. However, I am unable to find it. Can you please point me out the location where I can find the code to calculate Average-mAP?

**Comment by SilvioGiancola** [comment]
Hi, Have you read the main README.md? There is a section on [Evaluation](https://github.com/SoccerNet/sn-spotting#evaluation). We have shared [here](https://github.com/SoccerNet/sn-spotting/tree/main/Evaluation) code to evaluate your performances.

**Comment by avijit9** [comment]
Yes, I have read that part of the README.md.  I wanted to know is the definition of the `evaluate` method which is inside the `SoccerNet.Evaluation.ActionSpotting` module. 

Sorry if it seems to be confusing!

**Comment by SilvioGiancola** [comment]
Gotcha! It comes from the SoccerNet pip package, that we have not released publicly (only because the github repo that hosts the package contains private information we don't want to release yet). Still, you can check the source files once SoccerNet is installed with pip in a conda environment. The files are installed somewhere in your computer, it's just a matter of finding it.
